version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sprint
      POSTGRES_PASSWORD: sprint
      POSTGRES_DB: sprint
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sprint"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: sprint
      DB_PASSWORD: sprint
      DB_NAME: sprint
      WEB_ORIGIN: http://localhost:3000
      JWT_SECRET: dev-secret
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/docs"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
