services:
  - type: web
    name: sprintsync-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: corepack enable && pnpm install --frozen-lockfile=false && pnpm -w turbo run build --filter=@sprintsync/api
    startCommand: bash -lc 'node apps/api/dist/scripts/seed.js && node apps/api/dist/main.js'
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sprintsync-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: WEB_ORIGIN
        value: https://your-vercel-domain.vercel.app
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /docs

databases:
  - name: sprintsync-db
    plan: free
    region: oregon


